include hyde.conf
# Add your custom configurations here
shell zsh

font_family      CaskaydiaCove Nerd Font
# font_family Iosevka Nerd Font
font_size 14.0
bold_font auto

# URL 
undercurl_style thin-dense
url_style curly
show_hyperlink_targets yes

term xterm-256color
background_opacity 0.80
dynamic_background_opacity no
background_blur 5


# Cursor 
cursor_trail 10
cursor_trail_start_thresold 0
cursor_trail_decay 0.01 0.06
